<link rel="apple-touch-icon-precomposed" sizes="152x152" href="/<?=$directory?>/apple-touch-icon-152x152-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/<?=$directory?>/apple-touch-icon-144x144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="/<?=$directory?>/apple-touch-icon-120x120-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/<?=$directory?>/apple-touch-icon-114x114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="/<?=$directory?>/apple-touch-icon-76x76-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/<?=$directory?>/apple-touch-icon-72x72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/<?=$directory?>/apple-touch-icon-precomposed.png">